import * as fs from 'fs';
import * as path from 'path';
import * as vscode from 'vscode';

const DEVNOTES_FILENAME = '.devnotes';

export interface DiscoveryResult {
    devnotesPaths: string[];
    diagramPaths: string[];
    workspaceRoot: string;
}

export async function discoverDevnotesAndDiagrams(): Promise<DiscoveryResult | null> {
    const folders = vscode.workspace.workspaceFolders;
    if (!folders?.length) return null;
    const root = folders[0].uri.fsPath;
    const devnotesPaths: string[] = [];
    const diagramPaths: string[] = [];

    async function walk(dir: string): Promise<void> {
        let entries: fs.Dirent[];
        try {
            entries = await fs.promises.readdir(dir, { withFileTypes: true });
        } catch {
            return;
        }
        for (const e of entries) {
            const full = path.join(dir, e.name);
            if (e.isDirectory()) {
                if (e.name === 'node_modules' || e.name === '.git') continue;
                await walk(full);
            } else if (e.isFile()) {
                if (e.name === DEVNOTES_FILENAME) devnotesPaths.push(full);
                if (e.name.endsWith('.mermaid') || (e.name.endsWith('.md') && e.name !== DEVNOTES_FILENAME)) {
                    diagramPaths.push(full);
                }
            }
        }
    }

    await walk(root);
    return { devnotesPaths, diagramPaths, workspaceRoot: root };
}

export async function readFileSafe(filePath: string): Promise<string> {
    try {
        return await fs.promises.readFile(filePath, 'utf8');
    } catch {
        return '';
    }
}

export async function buildAggregatedDocument(result: DiscoveryResult): Promise<string> {
    const sections: string[] = ['# Holistic .devnotes\n', 'Generated by Devnotes extension.\n'];
    for (const p of result.devnotesPaths) {
        const rel = path.relative(result.workspaceRoot, p);
        const content = await readFileSafe(p);
        sections.push(`## ${rel}\n\n${content}\n`);
    }
    sections.push('---\n## Diagram references\n');
    for (const p of result.diagramPaths) {
        const rel = path.relative(result.workspaceRoot, p);
        sections.push(`- ${rel}\n`);
    }
    return sections.join('\n');
}

export async function writeTopLevelDevnotes(workspaceRoot: string, content: string): Promise<void> {
    const topPath = path.join(workspaceRoot, DEVNOTES_FILENAME);
    await fs.promises.writeFile(topPath, content, 'utf8');
}
